name: Deploy Bonds API Prod

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string

env:
  AWS_REGION: "us-east-1"
  ECR_REPOSITORY: bonds-api-prod
  ENVIRONMENT: PROD
  GH_USER_TOKEN: ${{ secrets.GH_USER_TOKEN }}
  GH_USER_NAME: ${{ secrets.GH_USER_NAME }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v2
      - run: sleep 5